language: node_js
node_js:
- '0.12'
before_install:
- npm install -g bower
before_script:
- npm install
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: VTJTgofeb2WvVrL1dBhjCa3xrVjzb/xtAkOKEhJwtXrPf7NdOVRngtyX9T95butaX3n/8C7yo36NrsyAzKirZlenuW9vXhRxHb1F0eL1CsdJrpm/D/d856Mu06xJKW1WQYi22aCAZuW+dczSR5ICO/kvyEF/HJjH+pyhmcoQWadv2bOxFgBvturu+ysaxy7/AGZ4IyjaWbfpWoq/xUQmp8wzLDAym9ZlS5EyD9OG3hZ4BEgO+/cxfGodKxyYpQT0Og5Wu40pb2jgwkx/TeGqLdXVyMlOntTDN/Lm0KmOjWmCqIfa8ZThH/p2zbKCRcJCsXpUh1xHX31vBM4MR4CnYzYoQyZ1dHH/UBtAVVXJMysRU3orabrfB7O0rYAeAUu569as+H0zgDsxgHsHLycQNuEuqMiCo7aLHzjifusrmL/V3sYnOnVNFWzIphO833z0Q5R6JgtyC1SRLSl0MRNan1UqGm2X/8K2mudLiSxGrtnuW7EgVVZLSyxjWdnSTUjO2m3q447JfP8en1E0AdrL/RkxlEqCqdyn+biFIJY87dmvIJA586mjZrU4z5LlUqFI0d7hpLuEOaNAiBBwrmDBe0HufYYs9Bgd9gnChhQZWozkizTuOdQF8OaxyyMOFfMftA1KMyj6W3cZh9y2Ge35uWnyLFJennkllWcmk3HaD9o=
  app: mood--music